### PR TITLE
* Add credentials issuers headers to /judge responses.

### PR DESCRIPTION
**Pull request by jfardello**
Signed-off-by: José Fardello <jmfardello@gmail.com>

This PR adds credentials issuers headers for /judge, while the handler_test passes, I did not include any test.. I can't figure out how to properly configure NewCredentialsIssuerHeaders() in order to test this.

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you for the contribution! I definitely understand the approach but am thinking if there is a better way to approach this. I'll let you know once I have some ideas. By the way, we should also do this for the cookie credential issuer!

**Comment by ngrigoriev** [comment]
I am wondering if it is possible to integrate this into Oathkeeper. The lack of this feature prevents me from using it with Ambassador API Gateway.

**Comment by aeneasr** [comment]
Yeah, I'll work on this over the weekend!

**Comment by ngrigoriev** [comment]
Thanks! About to try it from master. Any chances of new Oathkeeper release any time soon? ;)

**Comment by ngrigoriev** [comment]
@aeneasr tested - works like charm, thanks again!

**Comment by aeneasr** [comment]
Yes, preparing releases this week. Hopefully we’ll get it done by OEW. Glad it works as expected!

**Pull request closed without merging**
