### PR TITLE
feat: Enable configuration of timeout settings for oauth2_client_credentials authoriser

### PR DESCRIPTION
**Pull request by catper**
## Related issue

#442

This was also briefly discussed with @aeneasr [on Slack](https://app.slack.com/client/T010GP8ELBT/C01340V8KSM/thread/C01340V8KSM-1589898335.074600) 

## Proposed changes
Enable users to specify timeout for the oauth2_client_credentials authoriser, much in the same fashion as is possible for the oauth2_introspection authoriser.

## Checklist
- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

## Further comments
A lot of changes were generated when running `npm gen docs`, which creates rather a lot of noise. Sorry about that.

### CODE REVIEW

**Comment by catper** [comment]
Not sure what the failing test is about, I didn't change any dependencies. If anyone can help me sort this it out would be much appreciated!

**Comment by aeneasr** [comment]
```
go get github.com/gorilla/websocket@v1.4.2
```

in the project root should resolve this!

**Comment by catper** [comment]
> go get github.com/gorilla/websocket@v1.4.2

that did indeed sort this out, thanks!

**Comment by imranismail** [comment]
Nicely done, I was about to work on this :)

**Comment by aeneasr** [comment]
Awesome 🎉 

Thank you for your contribution!

**Pull request merged**
