### PR TITLE
docs: fix "decisions" typo in Introduction

### PR DESCRIPTION
**Pull request by AugPro**
Fix documentation typo quoting `/decision` instead of `/decisions`

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by vinckr** [comment]
Thanks for keeping an eye out @AugPro !
As soon as you sign the CLA we can merge this and send you a welcome gift for your first contribution 🎉

**Comment by vinckr** [comment]
Oh and could you make the same change in the newest versioned document please 🙏 
You can find it here:
https://github.com/ory/oathkeeper/blob/master/docs/versioned_docs/version-v0.38/index.md

**Comment by AugPro** [comment]
Sounds good ! Will do @vinckr

**Comment by aeneasr** [comment]
🙏

**Pull request merged**
