### PR TITLE
feat: Enable tracing

### PR DESCRIPTION
**Pull request by ptescher**
## Proposed changes

Enable tracing via ory/x/tracing just like Hydra etc.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation within the code base (if appropriate)
- [x] I have documented my changes in the [developer guide](https://github.com/ory/docs) (if appropriate)

### CODE REVIEW

**Comment by aeneasr** [comment]
Cool! Could you maybe add a jaeger example to the docker compose file similar to the way we have done it for Hydra (see [code](https://github.com/ory/hydra/blob/master/quickstart-tracing.yml))? That would be super helpful to check out the feature!

**Comment by ptescher** [comment]
@aeneasr done!

**Comment by ptescher** [comment]
image

**Comment by aeneasr** [comment]
Awesome, thank you!

**Comment by snikch** [comment]
FYI this capability isn't in the docs so it was a nice surprise to find this PR!

Confirming though, this doesn't add the spans to outgoing requests from Oathkeeper does it? i.e. it won't allow be to continue tracing through to Hydra.

**Comment by daviddelucca** [comment]
@snikch does it work? I have set jaeger but I don't see oathkeeper requests to upstream or mutator

**Comment by snikch** [comment]
@daviddelucca works fine for us 
image

**Comment by daviddelucca** [comment]
@snikch

I'm just seeing request for [introspection](https://github.com/ory/oathkeeper/blob/master/pipeline/authn/authenticator_oauth2_introspection.go#L208). Are you able to find tracing for upstream host requests?

**Comment by snikch** [comment]
@daviddelucca ah yes, correct. I added this separately here: https://github.com/ory/oathkeeper/pull/640 

You'd need to have the equivalent code added to other endpoints I think. A bigger refactor would be to use a shared http client with tracing enabled so each separate area doesn't need to have it implemented.

**Pull request merged**
