### PR TITLE
feat: Enable custom cache key support for Hydrator

### PR DESCRIPTION
**Pull request by anderslauri**
The cache key for `hydrator` is composed of the whole `AuthenticationSession` - this is not optimal. This PR provides the ability to opt-in to a special cache key as (as part of) `AuthenticationSession` for more fine granular cache control

## Related issue(s)
- None what I found.
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by anderslauri** [comment]
Not sure why tests are failling, looks like a `swagger` issue.

**Comment by anderslauri** [comment]
OK, now some bash-script for E2E-tests are failing, `killall` is not found also some file generation or a path is incorect.

**Comment by anderslauri** [comment]
🤔 

Looks like there is no actual coverage for the cache by the existing tests.

**Review by aeneasr — CHANGES_REQUESTED** [review]
Not sure if this is intentional but this would use exactly one cache key per route for all requests. Using custom cache keys is extremely dangerous because it can lead to results which say someone is allowed to do something while in fact they are not.

We had this problem already in Oathkeeper which is why i am very reluctant to merge changes to the cache behavior. I hope you understand!

If I misunderstood the use case here please LMK :)

**Comment by anderslauri** [comment]
> We had this problem

Maybe I missunderstood the flexible configuration. Let us be transparent - if one chooses to have a static cache key, naturally as you describe the situation would be correct. However I was under the assumption one can do, i.e. `{{ print .Subject }}` and thus that would be the individual subject on the `AuthenticationSession` - if this is shared or not - in the end it is in the hand of the consumer. However, given this flexiblity provides a more custom approach to set a cache key beyond the whole `AuthenticationSession`.

**Comment by aeneasr** [comment]
The value `cfg.Cache.Key` is static globally, and can be overwritten per route. Payloads or sessions have no effect on it. You would thus always get the same result for any request to the specified route(s), regardless of your payloads.

**Comment by anderslauri** [comment]
Thank you,

Then my fundamental assumption was incorrect! PR as-is now have little
value, let me give this some thought as we would require a bit of
flexibility here.

**Comment by aeneasr** [comment]
Thank you for contributing :) In that case, I'll close this PR and am looking forward to your next contribution :)

**Comment by anderslauri** [comment]
> The value `cfg.Cache.Key` is static globally, and can be overwritten per route. Payloads or sessions have no effect on it. You would thus always get the same result for any request to the specified route(s), regardless of your payloads.

Following up here. OK, I understand the issue you are finally describing. I will try to rephrase this for myself.

1. `Subject A` is using `Route A` proxied through oathkeeper where one part of the pipeline is `hydrator`, this response is cached with the key `Subject A`. The entire `AuthenticationSession` is cached.
2. `Subject A` is using a another system and is routed using `Route B`, as the cache key is `print .subject` the `AuthenticationSession` from `Route A` would be the response and thus could include bad data.

Assuming the above is correct. A cache key can still be composed to be uniquely enough to work, however, yes it can be fragile. The follow up question would be, as the layout is today within the code, the pipeline (a defined set of routes) - does this have an unique identifier which can be accessed? If so the one can form a composite key (cache key + pipeline|route id) - assuming such exists?

**Pull request closed without merging**
