### PR TITLE
feat : Docker compose improvement

### PR DESCRIPTION
**Pull request by err0r500**
## Related issue
#488 

## Proposed changes

This PR should allow the docker-compose to run out of the box.

It uses a temporary container (busybox) to copy the content of `./.docker_compose/` into a named volume used by oathkeeper

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by aeneasr** [comment]
What's the difference between using an intermediate volume to copy the files, and mounting the files directly? What type of permission issue do you encounter? Does it have to do with the user ID?

**Comment by err0r500** [comment]
Hi,
As I mentioned in the related issue #490 it's a problem with SELinux and adding the `Z` flag is in fact enough.

I think the work around was working because SELinux doesn't care if you just copy files without trying to read/write them and once they were in the named volume, SELinux doesn't care at all of what you do with these files.

**Comment by aeneasr** [comment]
Ok great, in that case it would probably make sense to document this limitation of SELinux somewhere around [here](https://github.com/ory/oathkeeper/blob/master/docs/docs/configure-deploy.md#configure), for example:

```
:::note

Make sure to have the `Z` flag enabled when running this with SELinux enabled.

:::
```

It would probably make sense to say how to enable the `Z` flag as well (chmod?) :)

**Comment by err0r500** [comment]
Unfortunately, the `Z` flag must be set in the docker-compose file, like so : 

```
    volumes:
      - ./.docker_compose:/etc/config/oathkeeper:Z
```

here's the explanation : https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/

**Comment by aeneasr** [comment]
Oh I see, so maybe explain that and link to the article?

**Comment by err0r500** [comment]
It can be an option, yes. 

I was about to say it was not super user-friendly, especially if the change doesn't affect the other users... but since it looks like I'm the first one to hit the problem (and it's of course in all Ory's projects) SELinux must be disabled on pretty much everyone's machine :)

**Comment by aeneasr** [comment]
Yeah I don't think this was reported anywhere else although we did have some issues with ORY Kratos but I think it was related to how the image was set up. If we can guarantee that the flag does not have any negative behavior on other platforms (macOS, not SELinux, windows) we can also just merge it as is. Do you have access to any of those OS?

**Comment by err0r500** [comment]
yeap, I can find both, I'll tell you before the end of the day (Paris time)

**Comment by aeneasr** [comment]
Closing due to inactivity

**Pull request closed without merging**
