### PR TITLE
docs: Warn that gzip is unsupported

### PR DESCRIPTION
**Pull request by danrods**
Note to users that gzip responses are as of now unsupported for Cookie and Bearer authenticators. 
The result is that the `subject` and `extra` will not be filled in, and will fail silently.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Review by aeneasr — CHANGES_REQUESTED** [review]
Golang handles gziped HTTP response bodies automatically so this is supported. Maybe your response is missing the appropriate content encoding headers (and maybe also not respecting the request headers although that could be a bug in our forward logic).

Can you share your HTTP Response Headers?

**Comment by danrods** [comment]
@aeneasr Thank you for the review

I would have assumed so as well. This stemmed from a discussion we had in the oathkeeper slack channel
https://ory-community.slack.com/archives/C01340V8KSM/p1632166348046700

In this thread you can see the response headers I was sending
https://ory-community.slack.com/archives/C01340V8KSM/p1632237741052700?thread_ts=1632213654.049300&cid=C01340V8KSM

It contains the proper `Content-Encoding` header for `gzip`. We've been using this gzip compression filter in production for a long time and have never had issues. The only thing I know is that when the response is compressed the `AuthenticationSession` is not filled in with the body of the response, but after I removed the compression it is. 

I wanted to update the docs because theres no indication that there was a failure, I just couldn't print out the subject

**Comment by aeneasr** [comment]
Hm strange, thank you in that case! I have opened an issue to track this :)

**Comment by danrods** [comment]
Sounds good! Should I close this PR then, or should we add to the docs temporarily until it can be addressed? @aeneasr

**Comment by aeneasr** [comment]
I'll merge this one so people can at least troubleshoot :) Thank you! :)

**Pull request merged**
